#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# Defaults
: "${LOGOUTPUT:=/dev/stdout}"

if [[ $LOGOUTPUT == *"/"* ]]; then
  echo "syslogd >> Setting syslogd output to ${LOGOUTPUT}"
  exec syslogd -n -O "${LOGOUTPUT}" -S
else 
  echo "syslogd >> Setting syslogd output to remote server ${LOGOUTPUT}"
  exec syslogd -n -R "${LOGOUTPUT}" -S
fi
