#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# create crontab

cat << 'EOF' | tee /etc/crontab
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

*/1 *   * * *   root    cp /etc/postfix/conf.d/header_checks /etc/postfix/header_checks && postfix reload
*/1 *   * * *   root    cp /etc/postfix/conf.d/bad_recipients /etc/postfix/bad_recipients && postmap /etc/postfix/bad_recipients

EOF

cron -f
