#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

# Fix issue with dpkg-reconfigure and locales not installed "perl: warning: Setting locale failed."
unset LANG

sleep 10 # wait for postfix started.

# set var

MRENV=${ENV:-$WEIYUN_ENV}
label=mailrelay_${MRENV}_queue
instance_name=$(hostname)

echo "Starting checkqueue process..."

checkqueue(){
  queuelength=0
  result=`/usr/sbin/postqueue -p | tail -n 1`
  if [[ $result == *"Requests"* ]]; then
    queuelength=`echo $result | awk '{print $5}'`
  fi
  echo $queuelength > /home/work/queuelength
  echo "$label $queuelength" | curl --data-binary @- https://noc-monitor.dev.weiyun.baidu.com:8957/pg/metrics/job/pushgateway/instance/$instance_name
  # echo "$label $queuelength $instance_name"
}

MASTER_PID="$(cat /var/spool/postfix/pid/master.pid)"
while kill -0 "${MASTER_PID}" 2>/dev/null; do
  checkqueue
  sleep 5
done
